name: 📖 Documentation Improvement
description: Suggest improvements to our documentation
title: "[Docs]: "
labels: [Documentation]
assignees:
- Nikhila
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this documentation improvement request!
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue realated to this already exists.
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  attributes:
    label: What type of change are you suggesting?
    description: Please select the type of change are you suggesting
    options:
    - label: Images improper
    - label: Section improvement
    - lable: video improvement
      required: true
- type: input
  attributes:
    label: Documentation Link 
    description: Add a link to the page which needs improvement (if relevant)
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe the problem
    description: Is the documentation missing? Or is it confusing? Why is it confusing?
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the improvement
    description: A clear and concise description of the improvement.  
  validations:
    required: true
